name: Generate PDF

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Cache node_modules and Puppeteer Chromium
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache/puppeteer
        key: ${{ runner.os }}-puppeteer-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-puppeteer-

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Generate PDF directly into gh-pages
      run: node hello-framework/scripts/generate-uvod-pdf.js

    - name: Commit and push PDF to gh-pages
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add uvod.pdf
        git commit -m "🚀 Dodan uvod.pdf [auto]" || echo "No changes to commit"
        git push
