name: Generate Combined PDF

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Generate combined PDF
      run: node scripts/generate-single-pdf.js

    - name: Commit and push PDF
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add pdf/uvod_sve_stranice.pdf
        git commit -m "Ažuriran objedinjeni PDF iz više linkova"
        git push
